import { defineStore } from 'pinia';
import { BeltColors, Technique } from 'src/models/Technique';

export const useKenpoStore = defineStore('kenpo', {
  state: () => ({
    techniques: [
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Delayed Sword',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Alternating Maces',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Sword of Destruction',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Deflecting Hammer',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Captured Twigs',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Grasp of Death',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Checking the Storm',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Mace of Aggression',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Attacking Mace',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Sword and Hammer',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Clutching Feathers',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Triggered Salute',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Dance of Death',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Thrusting Salute',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Gift of Destruction',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Locking Horns',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Evading the Storm',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Lone Kimono',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Glancing Salute',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Five Swords',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Scraping Hoof',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Grip of Death',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Repeating Mace',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Shielding Hammer',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Striking Serpents Head',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Crashing Wings',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Twirling Wings',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Snapping Twig',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Leaping Crane',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Buckling Branch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Crushing Hammer',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Captured Leaves',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Calming the Storm',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Crossing Talon',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Reversing Mace',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Thrusting Prongs',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Locked Wings',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Obscure Wings',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Raining Claw',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Spiraling Twig',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Twisted Twig',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Obscure Sword',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Twin Kimono',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Parting Wings',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Thundering Hammers',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Swinging Pendulum',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Squeezing the Peach',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Circling Wing',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Obstructing the Storm',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Darting Mace',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Hooking Wings',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Shield and Sword',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Gift in Return',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Bow of Compulsion',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Charging Ram',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Sleeper',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Cross of Destruction',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Flight to Freedom',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Begging Hands',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Thrusting Wedge',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Flashing Wings',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Hugging Pendulum',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Repeated Devastation',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Destructive Twins',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Defying the Storm',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Crossed Twigs',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Snaking Talon',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Shield and Mace',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Retreating Pendulum',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Tripping Arrow',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Wings of Silk',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Conquering Shield',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Entangled Wing',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Raking Mace',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Dominating Circles',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Twist of Fate',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Flashing Mace',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Detour from Doom',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Gift of Destiny',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Blinding Sacrifice',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Returning the Storm',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Glancing Spear',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Encounter with Danger',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Gathering Clouds',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Circle of Doom',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Squatting Sacrifice',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Fallen Cross',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Brushing the Storm',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Desparate Falcons',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Circling the Horizons',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Gripping Talon',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Broken Ram',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Circling Destruction',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Obscure Claw',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Menacing Twirl',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Leap frm Danger',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Circles of Protection',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Rotating Destruction',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Broken Gift',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Escape from Death',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Capturing the Storm',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Intercepting the Ram',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Back Breaker',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Deceptive Panther',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Twirling Sacrifice',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Heavenly Assent',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Securing the Storm',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Falling Falcon',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Taming the Mace',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Defensive Cross',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Cross of Death',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Kneel of Compulsion',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Bowing to Buddha',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Glancing Wing',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Fatal Cross',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Thrust into Darkness',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Circling Fans',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Dance of Darkness',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Falcons of Force',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Bear and the Ram',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Clipping the Storm',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Circling Windmills',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Leap of Death',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Protecting Fans',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Reversing Circles',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Courting the Tiger',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Gathering of the Snakes',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Raining Lance',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Destructive Fans',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Unfurling Crane',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Unwinding Pendulum',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Grasping Eagles',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Parting of the Snakes',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Glancing Lance',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Destructive Kneel',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Entwined Maces',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Marriage of the Rams',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Ram and the Eagle',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Escape from the Storm',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Thrusting Lance',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Capturing the Rod',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Prance of the Tiger',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Fatal Deviation',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Snakes of Wisdom',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Reprimanding the Bears',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Entwined Lance',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Broken Rod',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Twirling Hammers',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Piercing Lance',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Unfolding the Dark',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Defying the Rod',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Escape from the Darkness',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Twisted Rod',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
    ] as Technique[],
    randomizeTechniques: false,
    overrideTimeToPerform: null as null | number,
  }),
  getters: {
    getTechniquesByBelt: (state) => {
      return (belt: BeltColors) => state.techniques.filter((technique) => technique.Belt === belt);
    },
    getFilteredTechniques: (state) => state.techniques.filter((technique) => technique.IncludedInFlashcards === true),
  },
});
