import { defineStore } from 'pinia';
import { BeltColors, Technique } from 'src/models/Technique';

export const useKenpoStore = defineStore('kenpo', {
  state: () => ({
    techniques: [
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Delayed Sword',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Alternating Maces',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Sword of Destruction',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Deflecting Hammer',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Captured Twigs',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Grasp of Death',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Checking the Storm',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Mace of Aggression',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Attacking Mace',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Sword and Hammer',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Clutching Feathers',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Triggered Salute',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Dance of Death',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Thrusting Salute',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Gift of Destruction',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Locking Horns',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Evading the Storm',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Lone Kimono',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Glancing Salute',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Five Swords',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Scraping Hoof',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Grip of Death',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Repeating Mace',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Shielding Hammer',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Striking Serpents Head',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Crashing Wings',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Twirling Wings',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Snapping Twig',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Leaping Crane',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Buckling Branch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Crushing Hammer',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Captured Leaves',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Calming the Storm',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Crossing Talon',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Reversing Mace',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Thrusting Prongs',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Locked Wings',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Obscure Wings',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Raining Claw',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Spiraling Twig',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Twisted Twig',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Obscure Sword',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
    ] as Technique[],
    randomizeTechniques: false,
    overrideTimeToPerform: null as null | number,
  }),
  getters: {
    getTechniquesByBelt: (state) => {
      return (belt: BeltColors) => state.techniques.filter((technique) => technique.Belt === belt);
    },
    getFilteredTechniques: (state) => state.techniques.filter((technique) => technique.IncludedInFlashcards === true),
  },
});
