import { defineStore } from 'pinia';
import { BeltColors, Technique } from 'src/models/Technique';

export const useKenpoStore = defineStore('kenpo', {
  state: () => ({
    techniques: [
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Delayed Sword',
        OpponentInteraction: 'front-right hand lapel grab',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Alternating Maces',
        OpponentInteraction: 'front-two hand push',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Sword of Destruction',
        OpponentInteraction: 'front-left straight or roundhouse punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Deflecting Hammer',
        OpponentInteraction: 'front right thrust kick',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Captured Twigs',
        OpponentInteraction: 'rear-bear hug-arms pinned',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Grasp of Death',
        OpponentInteraction: 'left flank-right arm headlock',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Checking the Storm',
        OpponentInteraction: 'front-right step through overhead club',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Mace of Aggression',
        OpponentInteraction: 'front-two hand lapel grab-pulling in',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Attacking Mace',
        OpponentInteraction: 'front-right step through straight punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Yellow,
        TechniqueName: 'Sword and Hammer',
        OpponentInteraction: 'right flank-left hand shoulder grab',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Clutching Feathers',
        OpponentInteraction: 'front-left hand hair grab',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Triggered Salute',
        OpponentInteraction: 'front-right hand direct push',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Dance of Death',
        OpponentInteraction: 'front-right hand straight punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Thrusting Salute',
        OpponentInteraction: 'front-right step through kick',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Gift of Destruction',
        OpponentInteraction: 'handshake',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Locking Horns',
        OpponentInteraction: 'front-headlock',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Evading the Storm',
        OpponentInteraction: 'front-right step through overhead club',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Lone Kimono',
        OpponentInteraction: 'front-left hand lapel grab',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Glancing Salute',
        OpponentInteraction: 'front-right step through round house punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Five Swords',
        OpponentInteraction: 'front-right step through round house punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Scraping Hoof',
        OpponentInteraction: 'full nelson',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Grip of Death',
        OpponentInteraction: 'left flank-right arm headlock',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Repeating Mace',
        OpponentInteraction: 'front-left hand push',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Shielding Hammer',
        OpponentInteraction: 'front-left step through hooking punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Striking Serpents Head',
        OpponentInteraction: 'front-bear hug, arms free',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Orange,
        TechniqueName: 'Crashing Wings',
        OpponentInteraction: 'rear-bear hug, arms free',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Twirling Wings',
        OpponentInteraction: 'rear two hand stiff arm-shoulder grab',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Snapping Twig',
        OpponentInteraction: 'front left-hand chest push',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Leaping Crane',
        OpponentInteraction: 'front right step through punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Buckling Branch',
        OpponentInteraction: 'front-left step through kick',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Crushing Hammer',
        OpponentInteraction: 'rear-bear hug-arms pinned',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Captured Leaves',
        OpponentInteraction: 'front-right finger lock',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Calming the Storm',
        OpponentInteraction: 'front-right step through roundhouse club',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Crossing Talon',
        OpponentInteraction: 'front-right t right wrist grab',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Reversing Mace',
        OpponentInteraction: 'front-left step through straight punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Thrusting Prongs',
        OpponentInteraction: 'front-bear hug-arms pinned',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Locked Wings',
        OpponentInteraction: 'rear-hammerlock',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Obscure Wings',
        OpponentInteraction: 'right flank-left hand shoulder grab',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Raining Claw',
        OpponentInteraction: 'front-right uppercut punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Spiraling Twig',
        OpponentInteraction: 'high rear-bear hug arms free',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Twisted Twig',
        OpponentInteraction: 'front-wrist lock',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Purple,
        TechniqueName: 'Obscure Sword',
        OpponentInteraction: 'right flank-rear shoulder grab',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Twin Kimono',
        OpponentInteraction: 'front-two hand lapel grab',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Parting Wings',
        OpponentInteraction: 'front-two hand push',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Thundering Hammers',
        OpponentInteraction: 'front-right step through punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Swinging Pendulum',
        OpponentInteraction: 'front-right roundhouse kick',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Squeezing the Peach',
        OpponentInteraction: 'rear-bear hug-arms pinned',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Circling Wing',
        OpponentInteraction: 'rear-two hand chock-arms bent',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Obstructing the Storm',
        OpponentInteraction: 'front-right step through overhead club',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Darting Mace',
        OpponentInteraction: 'front-two hand wrist grab',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Hooking Wings',
        OpponentInteraction: 'front-two hand low push',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Shield and Sword',
        OpponentInteraction: 'front-left step through punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Gift in Return',
        OpponentInteraction: 'front-handshake',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Bow of Compulsion',
        OpponentInteraction: "front-wrist lock against opponent's chest",
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Charging Ram',
        OpponentInteraction: 'front-tackle with arms close',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Sleeper',
        OpponentInteraction: 'front-right step through punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Cross of Destruction',
        OpponentInteraction: 'rear-two hand choke',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Blue,
        TechniqueName: 'Flight to Freedom',
        OpponentInteraction: 'rear-hammerlock',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Begging Hands',
        OpponentInteraction: 'front-two hand grab to wrist',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Thrusting Wedge',
        OpponentInteraction: 'front-two hand high push',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Flashing Wings',
        OpponentInteraction: 'front-right step through punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Hugging Pendulum',
        OpponentInteraction: 'front-right thrusting knife edge kick',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Repeated Devastation',
        OpponentInteraction: 'full nelson',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Destructive Twins',
        OpponentInteraction: 'front-two hand choke-pull in',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Defying the Storm',
        OpponentInteraction: 'front-right step through roundhouse club',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Crossed Twigs',
        OpponentInteraction: 'rear-two hand grab to wrists',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Snaking Talon',
        OpponentInteraction: 'left-right punch combo',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Shield and Mace',
        OpponentInteraction: 'front-right step through punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Retreating Pendulum',
        OpponentInteraction: 'front-right thrusting heal kick',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Tripping Arrow',
        OpponentInteraction: 'front-bearhug arms free',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Wings of Silk',
        OpponentInteraction: 'rear-two arm lock',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Conquering Shield',
        OpponentInteraction: 'front-left stiff-arm lapel grab',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Entangled Wing',
        OpponentInteraction: 'front-arm lock',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Green,
        TechniqueName: 'Raking Mace',
        OpponentInteraction: 'front-two hand lapel grab-pulling in',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Dominating Circles',
        OpponentInteraction: 'front-offset right-hand grab to right shoulder',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Twist of Fate',
        OpponentInteraction: 'front-hand push',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Flashing Mace',
        OpponentInteraction: 'front-right step through punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Detour from Doom',
        OpponentInteraction: 'front-right roundhouse kick',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Gift of Destiny',
        OpponentInteraction: 'front-handshake',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Blinding Sacrifice',
        OpponentInteraction: 'front-two hand shoulder grab',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Returning the Storm',
        OpponentInteraction: 'front-inward and outward club',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Glancing Spear',
        OpponentInteraction: 'front-right direct, left wrist grab',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Encounter with Danger',
        OpponentInteraction: 'front-two hand push',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Gathering Clouds',
        OpponentInteraction: 'front-right punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Circle of Doom',
        OpponentInteraction: 'front-right straight kick',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Squatting Sacrifice',
        OpponentInteraction: 'rear-bear hug arms free',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Fallen Cross',
        OpponentInteraction: 'rear-two hand choke',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Brushing the Storm',
        OpponentInteraction: 'right flank-step through overhead club',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Desparate Falcons',
        OpponentInteraction: 'front-two hand direct twist grabs to both wrists',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Circling the Horizons',
        OpponentInteraction: 'front-right step through punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Gripping Talon',
        OpponentInteraction: 'front-left direct grab to the right wrist',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Broken Ram',
        OpponentInteraction: 'front-tackle arms wide',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Circling Destruction',
        OpponentInteraction: 'front-left step through punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown3,
        TechniqueName: 'Obscure Claw',
        OpponentInteraction: 'right flank-left hand shoulder grab',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Menacing Twirl',
        OpponentInteraction: 'rear-left hand belt grab',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Leap from Danger',
        OpponentInteraction: 'rear-two hand push',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Circles of Protection',
        OpponentInteraction: 'front-right step through overhead punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Rotating Destruction',
        OpponentInteraction: 'front-right thrust & left spinning back kicks',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Broken Gift',
        OpponentInteraction: 'front-handshake',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Escape from Death',
        OpponentInteraction: 'right-rear arm choke',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Capturing the Storm',
        OpponentInteraction: 'front-right step through overhead club',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Intercepting the Ram',
        OpponentInteraction: 'front-tackle',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Back Breaker',
        OpponentInteraction: 'right flank-right step through punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Deceptive Panther',
        OpponentInteraction: 'right-front snap kick, low & high roundhouse',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Twirling Sacrifice',
        OpponentInteraction: 'full nelson',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Heavenly Assent',
        OpponentInteraction: 'front-two hand choke-arms straight',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Securing the Storm',
        OpponentInteraction: 'front-right step through roundhouse club',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Falling Falcon',
        OpponentInteraction: 'right-direct lapel grab',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Taming the Mace',
        OpponentInteraction: 'front-right step through punch with a wall behind you',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Defensive Cross',
        OpponentInteraction: 'front-right front snap kick',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Cross of Death',
        OpponentInteraction: 'front-two hand cross choke',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Kneel of Compulsion',
        OpponentInteraction: 'right flank-right step through punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Bowing to Buddha',
        OpponentInteraction: 'front-step through kick',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown2,
        TechniqueName: 'Glancing Wing',
        OpponentInteraction: 'front-left uppercut punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Fatal Cross',
        OpponentInteraction: 'front-two hand attempted low grab or push',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Thrust into Darkness',
        OpponentInteraction: 'rear-right step through punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Circling Fans',
        OpponentInteraction: 'front-left/right punch combination',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Dance of Darkness',
        OpponentInteraction: 'front-right kick & right punch combination',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Falcons of Force',
        OpponentInteraction: 'flank left & right shoulder grab/two attackers',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Bear and the Ram',
        OpponentInteraction: 'front-right punch/rear bear hug arms free/two attackers',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Clipping the Storm',
        OpponentInteraction: 'low front-right thrusting club',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Circling Windmills',
        OpponentInteraction: 'front-two hand push followed by right punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Leap of Death',
        OpponentInteraction: 'front-right step through straight punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Protecting Fans',
        OpponentInteraction: 'front-left & right punch combination',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Reversing Circles',
        OpponentInteraction: 'front-left roundhouse kick and left punch combination',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Courting the Tiger',
        OpponentInteraction: 'flank-left & right arm & shoulder grabs/two attackers',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Gathering of the Snakes',
        OpponentInteraction: 'front-left punch/rear right punch/two attackers',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Raining Lance',
        OpponentInteraction: 'front-right step through overhead knife attack',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Destructive Fans',
        OpponentInteraction: 'left-flank right step through punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Unfurling Crane',
        OpponentInteraction: 'front-left and right punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Unwinding Pendulum',
        OpponentInteraction: 'front-right kick and right punch combination',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Grasping Eagles',
        OpponentInteraction: 'front-right lapel grab/rear right shoulder grab/two attackers',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Parting of the Snakes',
        OpponentInteraction: 'front-right punch/rear attempt/two attackers',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Brown1,
        TechniqueName: 'Glancing Lance',
        OpponentInteraction: 'front-right shuffle knife thrust',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Destructive Kneel',
        OpponentInteraction: 'front-right step through punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Entwined Maces',
        OpponentInteraction: 'front-left right front punch combination',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Marriage of the Rams',
        OpponentInteraction: 'flank-right & left shoulder grabs/two attackers who are close to you',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Ram and the Eagle',
        OpponentInteraction: 'front-right punch & rear left-hand collar grab/two attackers',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Escape from the Storm',
        OpponentInteraction: 'right-flank right overhead club attack',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Thrusting Lance',
        OpponentInteraction: 'front-right step through low knife thrust',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Capturing the Rod',
        OpponentInteraction: 'front-right pistol against your chest',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Prance of the Tiger',
        OpponentInteraction: 'right-flank right step through uppercut punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Fatal Deviation',
        OpponentInteraction: 'front-right & right shoulder grabs/two attackers',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Snakes of Wisdom',
        OpponentInteraction: 'flank-left & right shoulder grabs/two attackers',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Reprimanding the Bears',
        OpponentInteraction: 'front-right punch & rear bear hug arms pinned/two attackers',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Entwined Lance',
        OpponentInteraction: 'front-right step through high knife thrust',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Broken Rod',
        OpponentInteraction: 'rear-right hand pistol against your back',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Twirling Hammers',
        OpponentInteraction: 'front-left step through punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Piercing Lance',
        OpponentInteraction: 'front-right knife thrust while your arms are up',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Unfolding the Dark',
        OpponentInteraction: 'rear-right flank left step through punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Defying the Rod',
        OpponentInteraction: 'front-right pistol',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Escape from the Darkness',
        OpponentInteraction: 'left-rear flank right step through punch',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
      {
        Belt: BeltColors.Black,
        TechniqueName: 'Twisted Rod',
        OpponentInteraction: 'front-right pistol',
        TimeToPerform: 5,
        IncludedInFlashcards: false,
      },
    ] as Technique[],
    randomizeTechniques: false,
    overrideTimeToPerform: null as null | number,
  }),
  getters: {
    getTechniquesByBelt: (state) => {
      return (belt: BeltColors) => state.techniques.filter((technique) => technique.Belt === belt);
    },
    getFilteredTechniques: (state) => state.techniques.filter((technique) => technique.IncludedInFlashcards === true),
  },
});
